#ifndef OPAQUEDB_CRYPTO_KEY_MATERIAL_H_
#define OPAQUEDB_CRYPTO_KEY_MATERIAL_H_

#include <string>
#include <string_view>
#include <vector>

#include "absl/status/statusor.h"
#include "opaquedb/crypto/context.h"
#include "seal/seal.h"

// Key material is the set of keys that cross the wire and let a node evaluate
// over a client's ciphertexts: the public key, the relinearization keys (the
// equality square and AND tree raise ciphertext size, relinearization brings it
// back), and the Galois keys (for the rotate-and-AND reduction, the masked
// broadcast, and the block-sum retrieve). The bit-sliced matcher needs all of
// them, so Galois keys are generated by default; they are the largest set, but
// the algorithm cannot run without rotations. The `galois_keys` field is empty
// only when a caller explicitly opts out. The secret key never appears here. It
// stays on the client and is why the operator never learns the value.

namespace opaquedb::crypto {

// The serialized public and evaluation keys, as they travel over the Register
// RPC and rest in the BlobStore. Opaque bytes to every layer above crypto.
struct KeyMaterial {
  std::string public_key;
  std::string relin_keys;
  std::string galois_keys;
};

// The full client-side keyset, including the secret key. Generated by the dev
// query tool and, later, by real clients. The server never holds one of these.
class ClientKeyring {
public:
  // Generates a fresh keyset bound to the given context. with_galois = true
  // generates the full power-of-two Galois set (large; for tests and benchmarks
  // that need arbitrary rotations); false generates none.
  static ClientKeyring Generate(const CryptoContext &ctx,
                                bool with_galois = true);

  // Generates a keyset whose Galois keys cover only the given rotation steps.
  // The bit-sliced matcher needs a small fixed set (see
  // core::RequiredGaloisSteps), so the client uses this to avoid sending the
  // full set. Empty means none.
  static ClientKeyring Generate(const CryptoContext &ctx,
                                const std::vector<int> &galois_steps);

  const seal::SecretKey &secret_key() const { return secret_key_; }
  const seal::PublicKey &public_key() const { return public_key_; }
  const seal::RelinKeys &relin_keys() const { return relin_keys_; }
  const seal::GaloisKeys &galois_keys() const { return galois_keys_; }

  // Serializes the public and evaluation keys for transport. The secret key is
  // deliberately not serializable through this path.
  absl::StatusOr<KeyMaterial> SerializePublic() const;

  // Serializes the ENTIRE keyset, including the secret key, for the client to
  // persist locally and reuse across runs. This is what lets a client register
  // its public and evaluation keys with the server once and then reuse the same
  // identity on later runs instead of generating a fresh keyset every time.
  //
  // This blob is the secret. It must never be sent to the server and must be
  // stored with owner-only permissions. It is the opposite of SerializePublic,
  // which is the wire form and omits the secret key on purpose.
  absl::StatusOr<std::string> SerializeAll() const;

  // Reconstructs a keyset previously produced by SerializeAll, binding it to
  // the context. The context must use the same parameters the keyset was
  // generated under, or loading is rejected with a status.
  static absl::StatusOr<ClientKeyring> LoadAll(const CryptoContext &ctx,
                                               std::string_view bytes);

private:
  ClientKeyring() = default;

  // Loads the materialized accessor copies back from the seeded bytes.
  void Materialize(const seal::SEALContext &context);

  seal::SecretKey secret_key_;
  seal::PublicKey public_key_;
  seal::RelinKeys relin_keys_;
  seal::GaloisKeys galois_keys_;
  // The seeded wire form of the public and evaluation keys, produced once at
  // generation time. SerializePublic hands these out directly; the materialized
  // copies above are loaded back from them for the local accessors.
  std::string public_key_bytes_;
  std::string relin_keys_bytes_;
  std::string galois_keys_bytes_;
  bool has_galois_ = false;
};

// The deserialized public and evaluation keys a node uses to evaluate. Bound to
// a context; deserialization validates each key against its parameters so a
// malformed or mismatched key is rejected before use, never crashing the node.
struct EvalKeys {
  seal::PublicKey public_key;
  seal::RelinKeys relin_keys;
  seal::GaloisKeys galois_keys;
};

absl::StatusOr<EvalKeys> LoadKeyMaterial(const CryptoContext &ctx,
                                         const KeyMaterial &material);

} // namespace opaquedb::crypto

#endif // OPAQUEDB_CRYPTO_KEY_MATERIAL_H_
