#ifndef OPAQUEDB_BACKEND_REFERENCE_REFERENCE_H_
#define OPAQUEDB_BACKEND_REFERENCE_REFERENCE_H_

#include <memory>
#include <vector>

#include "absl/status/statusor.h"
#include "opaquedb/backend/capabilities.h"
#include "opaquedb/backend/pir_backend.h"
#include "opaquedb/crypto/context.h"
#include "opaquedb/crypto/key_material.h"
#include "seal/seal.h"

// The reference PIR backend: bit-sliced equality matching with a plaintext-
// masked retrieve, on the BFV scheme, single server, semi-honest. It packs many
// records into the SIMD slots and evaluates them together, so the expensive
// ciphertext multiplies amortize across a whole batch.
//
// Slot layout: a ciphertext has N = poly_modulus_degree slots, in two rows of
// N/2 that rotate independently. Each record owns a block of key_bits
// contiguous slots within one row, so one ciphertext carries N / key_bits
// records. A record is binary-expanded into its block, bit i in slot
// block_start + i.
//
// Pipeline, per batch ciphertext:
//  1. The query arrives as one ciphertext: the lookup value's bits tiled across
//     every block. diff = query - key_plain (sub_plain), then sq = diff^2
//     (one ciphertext square) gives (q-k)^2, which is 0 where bits match and 1
//     where they differ. eq = 1 - sq is the per-bit XNOR.
//  2. AND-reduce eq across the block's key_bits bits by a rotate-and-multiply
//     tree of depth log2(key_bits): each level multiplies eq by a rotation of
//     itself, so the block-start slot ends holding the product of the whole
//     block, the equality indicator b_r. This and the square are the only
//     ciphertext-times-ciphertext multiplies: 1 + log2(key_bits) per batch,
//     independent of how many records the batch holds.
//  3. Mask to the block-start slots, then broadcast each indicator across its
//     block with masked rotations (no ciphertext multiply). For each payload
//     plane, multiply the broadcast indicator by the plane's packed payload and
//     block-sum into block 0 by rotate-and-add. Only the matching record's
//     block is nonzero, so the sum is its payload. Returns one ciphertext per
//     plane.
//  4. combine adds the per-shard, per-plane partials under encryption.
//
// Parameters and noise: the depth is 1 + log2(key_bits) ciphertext multiplies
// plus the plaintext multiplies of the masked retrieve. At the default
// key_bits = 16 that is depth 5, which exhausts the noise budget at
// poly_modulus_degree 8192, so the default degree is 16384 with a 349-bit
// coeff modulus, leaving a measured ~52-bit budget. The reference backend test
// asserts the remaining budget stays positive. Galois keys are required for the
// rotations and are generated by default.

namespace opaquedb::backend::reference {

// Forces the reference backend's static registration to be linked in when this
// symbol is referenced. Static libraries drop unreferenced translation units,
// so callers that want the registration call this once. Returns true.
bool LinkReferenceBackend();

class ReferenceBackend : public backend::PirBackend {
public:
  explicit ReferenceBackend(crypto::CryptoContext ctx);

  static backend::BackendCapabilities StaticCapabilities();
  backend::BackendCapabilities capabilities() const override;

  absl::StatusOr<std::unique_ptr<backend::EvalContext>>
  load_keys(const crypto::KeyMaterial &keys) override;

  absl::StatusOr<std::vector<seal::Ciphertext>>
  evaluate(backend::EvalContext &ctx, const backend::EncryptedQuery &query,
           const backend::KeyColumn &keys,
           const backend::PayloadColumns &payload) override;

  absl::StatusOr<std::vector<seal::Ciphertext>>
  combine(backend::EvalContext &ctx,
          std::vector<std::vector<seal::Ciphertext>> partials) override;

private:
  crypto::CryptoContext ctx_;
  std::shared_ptr<seal::Evaluator> evaluator_;
};

} // namespace opaquedb::backend::reference

#endif // OPAQUEDB_BACKEND_REFERENCE_REFERENCE_H_
